
service: reminders

provider:
  name: aws
  runtime: nodejs8.10

functions:
  membership:
    handler: membership.start
    events:
      - schedule: cron(0 11 ? * 7 *)
  rental:
    handler: rental.start
    events:
      - schedule: cron(0 11 ? * 3 *)
