
service: reminders

provider:
  name: aws
  runtime: nodejs6.10

functions:
  membership:
    handler: membership.start
    events:
      - schedule: cron(1 11 * * ? *)
  rental:
    handler: rental.start
    events:
      - schedule: cron(2 11 * * ? *)
