
service: reminders

provider:
  name: aws
  runtime: nodejs8.10

functions:
  membership:
    handler: reminders.membership
    events:
      - schedule: cron(0 11 ? * 7 *)
  rental:
    handler: reminders.rental
    events:
      - schedule: cron(0 11 ? * 3 *)
